# Generated by Django 6.1.1 on 2026-09-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_options_alter_fotografia_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
        migrations.DeleteModel(
            name='SolicitudCotizacion',
        ),
    ]
